[metadata]
nixpacksVersion = ">=1.0.0"

[phases.setup]
# fuerza la instalación de Node.js (y npm)
packages = ["nodejs", "npm"]

[phases.build]
# comandos a ejecutar en la fase de build
commands = [
  "npm ci",
  "npm run build"
]

[phases.start]
# comando para arrancar tu servidor
command = "npm run start"
